services:
  ledger-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ledger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '54321:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 20

  identity-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '54322:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 20

  ledger-api:
    build:
      context: .
      dockerfile: apps/ledger/Dockerfile
    environment:
      LEDGER_PORT: ${LEDGER_PORT}
      LEDGER_DB_URL: ${LEDGER_DB_URL}
      JWT_EXTERNAL_SECRET: ${JWT_EXTERNAL_SECRET}
      JWT_INTERNAL_SECRET: ${JWT_INTERNAL_SECRET}
      IDENTITY_INTERNAL_BASE_URL: ${IDENTITY_INTERNAL_BASE_URL}
    ports:
      - '3001:3001'
    depends_on:
      ledger-db:
        condition: service_healthy

  identity-api:
    build:
      context: .
      dockerfile: apps/identity/Dockerfile
    environment:
      IDENTITY_PORT: ${IDENTITY_PORT}
      IDENTITY_DB_URL: ${IDENTITY_DB_URL}
      JWT_EXTERNAL_SECRET: ${JWT_EXTERNAL_SECRET}
      JWT_INTERNAL_SECRET: ${JWT_INTERNAL_SECRET}
      LEDGER_INTERNAL_BASE_URL: ${LEDGER_INTERNAL_BASE_URL}
    ports:
      - '3002:3002'
    depends_on:
      identity-db:
        condition: service_healthy
